# Site settings
title: Greece
client:
  name: Visit Greece
  link: http://www.visitgreece.gr/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Greece, a mythical and enchanting destination that deserves a lifetime of exploration. From kicking back on famous beaches, with soft golden sands and iconic azure waters, to indulging in delicious Greek cuisine in a host of charming tavernas, a holiday to Greece caters easily to all tastes. A myriad of islands, bastions of their unique traditions, cultures, landscapes and flavours, act as stepping stones on an itinerary framed by diversity and intrepid adventuring.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/greece" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/greece/_assets/img"
css:     "/uk/2020/greece/_assets/css"
js:      "/uk/2020/greece/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed