# Site settings
title: Greece
description: >
  Greece, a mythical and enchanting destination that deserves a lifetime of exploration. From kicking back on famous beaches, with soft golden sands and iconic azure waters, to indulging in delicious Greek cuisine in a host of charming tavernas, a holiday to Greece caters easily to all tastes.
baseurl: "/greece" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md, npm-debug.log]
